### ISSUE TITLE
handle `service` with input parameters

### ISSUE THREAD

**Issue by bradrydzewski** [bradrydzewski/spec#12]
```yaml
  stages:
    - id: k8s-deploy
      runtime: cloud
      delegates: harshprodrunner
      platform:
        os: linux
        arch: amd64
      service:
        id: k8s_artifactory
        with:
          con: ShobhitGitConnector
      template:
        uses: RollingGlobalTemplate
```

option 1:

```yaml
service:
  uses: k8s_artifactory
  with: 
    connector: ShobhitGitConnector
```

option 2:

...
