### ISSUE TITLE
failure strategy should support one or many

### ISSUE THREAD

**Issue by bradrydzewski** [bradrydzewski/spec#13]
```
      on-failure:
      - errors: [connectivity]
        action: abort
      - errors: [unknown]
        action: retry
```
