### ISSUE TITLE
environment group support

### ISSUE THREAD

**Issue by bradrydzewski** [bradrydzewski/spec#14]
**Use Case 1**

Environment group, all environments, all infrastructures

```yaml
pipeline:
  service:
    items:
    - petstore-frontend
    - petstore-backend
  environment:
    group: my-group
```

Environment group, 1 environment, all infrastructures

```yaml
pipeline:
  service:
    items:
    - petstore-frontend
    - petstore-backend
  environment:
    group:
      name: my-group
      parallel: true
      items:
      - name: prod
        deploy-to: all
```

Environment group, 1 environment, 1 infrastructures

```yaml
pipeline:
  service:
    items:
    - petstore-frontend
    - petstore-backend
  environment:
    group:
      name: my-group
      parallel: true
      items:
      - name: dev
        deploy-to: infra3
```

Environment group, 1 environment, multiple infrastructures

```yaml
pipeline:
  service:
    items:
    - petstore-frontend
    - petstore-backend
  environment:
    group:
      name: my-group
      parallel: true
      items:
      - name: stage
        deploy-to:
        - infra1
        - infra2
```

Environment group, match environment, match infrastructure

```yaml
pipeline:
  service:
    items:
    - petstore-frontend
    - petstore-backend
  environment:
    group:
      name: my-group
      parallel: true
      items:
      - match: prod       # match any environment that contains "prod". e.g. this would match prod1, prod2
        deploy-to: infra  # match any infrastructure that contains "infra".  e.g. this would match infra1, infra2
```

---

Alternative

```yaml
pipeline:
  service:
    items:
    - petstore-frontend
    - petstore-backend
  environment:
    parallel: true
    group: foo          # add "group" to environment
    items:
    - name: prod
      deploy-to: all
    - name: stage
      deploy-to:
      - infra1
      - infra2
    - name: dev
      deploy-to: infra3

    # add "match" block to match environments
    - match: prod-us-*
    - match:         
        name:
        - prod-us-*
        - prod-eu-*
        deploy-to:
        - cluster-us-*
        - cluster-eu-*
  stages:
  - steps:
    - go build
```
